name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
          pip install pre-commit pytest build
      - name: Lint
        run: pre-commit run --files $(git ls-files '*.py')
      - name: Test
        run: pytest
      - name: Build
        run: python -m build
